# Generated by Django 4.2.7 on 2024-02-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('наличные', 'наличные'), ('карта', 'карта')], default='карта', max_length=25, verbose_name='способ оплаты'),
        ),
    ]
