# Generated by Django 4.2.7 on 2024-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_pay_url_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
